USE [JurassicPark]
GO

/****** Object:  Index [IX_Besucher_Person]    Script Date: 12.06.2023 22:02:41 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Besucher_Person] ON [dbo].[Besucher]
(
	[PersonID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


