USE [JurassicPark]
GO

/****** Object:  Table [dbo].[Uhr]    Script Date: 15.06.2023 09:08:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Uhr](
	[ZeitDatID] [int] IDENTITY(1,1) NOT NULL,
	[ZeitDatum] [datetime] NOT NULL,
 CONSTRAINT [PK_Uhr] PRIMARY KEY CLUSTERED 
(
	[ZeitDatID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Uhr] ADD  CONSTRAINT [DF_Uhr_ZeitDatum]  DEFAULT (getdate()) FOR [ZeitDatum]
GO


