USE [JurassicPark]
GO

/****** Object:  Index [IX_ZeitPos_GPS_Zeit]    Script Date: 15.06.2023 09:11:14 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_ZeitPos_GPS_Zeit] ON [dbo].[ZeitPos]
(
	[GPSID] ASC,
	[ZeitDatID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


