USE [JurassicPark]
GO

/****** Object:  Index [IX_ZeitPos_PositionID]    Script Date: 15.06.2023 09:11:42 ******/
CREATE NONCLUSTERED INDEX [IX_ZeitPos_PositionID] ON [dbo].[ZeitPos]
(
	[GPSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


