USE [JurassicPark]
GO

/****** Object:  Table [dbo].[DietTyp]    Script Date: 15.06.2023 08:37:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER TABLE [dbo].[DietTyp](
	[DietTypID] [int] IDENTITY(1,1) NOT NULL,
	[Dietname] [nvarchar](50) NOT NULL,
	[ParkteilID] [int] NOT NULL,
 CONSTRAINT [PK_Typ] PRIMARY KEY CLUSTERED 
(
	[DietTypID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[DietTyp]  WITH CHECK ADD  CONSTRAINT [FK_DietTyp_Parkteil] FOREIGN KEY([ParkteilID])
REFERENCES [dbo].[Parkteil] ([ParkteilID])
GO

ALTER TABLE [dbo].[DietTyp] CHECK CONSTRAINT [FK_DietTyp_Parkteil]
GO


