USE [JurassicPark]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [IX_Essen_Name]    Script Date: 15.06.2023 08:54:56 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Essen_Name] ON [dbo].[Essen]
(
	[Essensname] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


