USE [JurassicPark]
GO

/****** Object:  Table [dbo].[ZeitPos]    Script Date: 15.06.2023 09:08:58 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ZeitPos](
	[PosZeitID] [int] IDENTITY(1,1) NOT NULL,
	[GPSID] [int] NOT NULL,
	[ZeitDatID] [int] NOT NULL,
	[Koordinaten] [geography] NOT NULL,
 CONSTRAINT [PK_ZeitPos] PRIMARY KEY CLUSTERED 
(
	[PosZeitID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[ZeitPos] ADD  CONSTRAINT [DF_ZeitPos_Koordinaten]  DEFAULT (0xE6100000010C00000000000000000000000000000000) FOR [Koordinaten]
GO

ALTER TABLE [dbo].[ZeitPos]  WITH CHECK ADD  CONSTRAINT [FK_ZeitPos_Positionszuordnung] FOREIGN KEY([GPSID])
REFERENCES [dbo].[GPS] ([GPSID])
GO

ALTER TABLE [dbo].[ZeitPos] CHECK CONSTRAINT [FK_ZeitPos_Positionszuordnung]
GO

ALTER TABLE [dbo].[ZeitPos]  WITH CHECK ADD  CONSTRAINT [FK_ZeitPos_Uhr] FOREIGN KEY([ZeitDatID])
REFERENCES [dbo].[Uhr] ([ZeitDatID])
GO

ALTER TABLE [dbo].[ZeitPos] CHECK CONSTRAINT [FK_ZeitPos_Uhr]
GO


